loam_interface:
  ros__parameters:
    use_sim_time: True
    loam_odometry_topic: gt/mid360
    sensor_scan_topic: livox/lidar
    map_cloud_topic: pslam/lio_map_cloud
    odom_frame: odom
    base_frame: base_footprint
    lidar_frame: mid360
    robot_base_frame: base_link

terrain_analysis:
  ros__parameters:
    use_sim_time: True
    odom_frame: odom
    lidar_frame: mid360
    scan_voxel_size: 0.05
    decay_time: 2.0
    no_decay_dis: 4.0
    clearing_dis: 8.0
    use_sorting: True
    quantile_z: 0.25
    consider_drop: False
    limit_ground_lift: False
    max_ground_lift: 0.15
    clear_dy_obs: True
    min_dy_obs_dis: 0.3
    abs_dy_obs_rel_z_thre: 0.2
    min_dy_obs_vfov: -16.0
    max_dy_obs_vfov: 16.0
    min_dy_obs_point_num: 1
    min_out_of_fov_point_num: 2
    obstacle_height_thre: 0.15
    no_data_obstacle: False
    no_data_block_skip_num: 0
    min_block_point_num: 10
    vehicle_height: 0.6
    min_rel_z: -1.5
    max_rel_z: 0.2
    dis_ratio_z: 0.2
    voxel_point_update_thre: 100
    voxel_time_update_thre: 2.0

terrain_analysis_ext:
  ros__parameters:
    use_sim_time: True
    odom_frame: odom
    lidar_frame: mid360
    terrain_voxel_size: 2.0
    terrain_voxel_width: 41
    planar_voxel_size: 0.4
    planar_voxel_width: 101
    voxel_point_count_thre: 100
    ground_elevation_thre: 0.5
    use_terrain_dyn_thre: 1.5
    check_terrain_conn: True
    terrain_under_vehicle: -0.75
    ceiling_filtering_thre: 2.0
    local_terrain_map_radius: 4.0
    downsize_filter_corner: 0.2
    downsize_filter_surface: 0.1
    point_decay_period: 10
    point_decay_ratio: 0.5
    vertical_angle_thre: 0.0
    max_terrain_angle: 30.0
    ground_z_thre: 0.1

local_planner:
  ros__parameters:
    use_sim_time: True
    base_frame: base_link
    lidar_frame: mid360
    path_folder: $(find-pkg-share local_planner)/paths
    vehicle_length: 0.5
    vehicle_width: 0.5
    two_way_drive: true
    no_path_reverse: true
    laser_voxel_size: 0.05
    terrain_voxel_size: 0.2
    use_terrain_analysis: true
    check_obstacle: true
    check_rot_obstacle: false
    adjacent_range: 3.5
    obstacle_height_threshold: 0.15
    ground_height_threshold: 0.1
    cost_height_threshold: 0.1
    cost_score: 0.02
    use_cost: false
    point_per_path_threshold: 2
    min_relative_z: -0.6
    max_relative_z: 0.6
    max_speed: 1.0
    direction_weight: 0.02
    direction_threshold: 10.0
    direction_to_vehicle: true
    path_scale: 1.0
    min_path_scale: 0.75
    path_scale_step: 0.25
    path_scale_by_speed: true
    min_path_range: 1.0
    path_range_step: 0.5
    path_range_by_speed: true
    path_crop_by_goal: true
    autonomy_mode: false
    autonomy_speed: 1.0
    joy_to_speed_delay: 2.0
    joy_to_check_obstacle_delay: 5.0
    goal_clear_range: 0.5

path_follower:
  ros__parameters:
    use_sim_time: True
    base_frame: base_link
    lidar_frame: mid360
    pub_skip_num: 1
    two_way_drive: true
    look_ahead_distance: 0.5
    yaw_rate_gain: 7.5
    stop_yaw_rate_gain: 7.5
    max_yaw_rate: 45.0
    max_speed: 1.0
    max_acceleration: 1.0
    switch_time_threshold: 1.0
    direction_diff_threshold: 3.1
    stop_distance_threshold: 0.2
    slow_down_distance_threshold: 1.0
    use_inclination_rate_to_slow: false
    inclination_rate_threshold: 120.0
    slow_rate_1: 0.25
    slow_rate_2: 0.5
    slow_time_1: 2.0
    slow_time_2: 2.0
    use_inclination_to_stop: false
    inclination_threshold: 45.0
    stop_time: 5.0
    no_rotation_at_stop: false
    no_rotation_at_goal: true
    autonomy_mode: false
    autonomy_speed: 1.0
    joy_to_speed_delay: 2.0

far_planner:
  ros__parameters:
    use_sim_time: True
    # Dynamic Planner Default Params
    main_run_freq: 5.0
    voxel_dim: 0.1  # Unit: meter
    robot_dim: 0.5   # Unit: meter
    vehicle_height: 0.6  # Unit: meter
    sensor_range: 15.0  # Unit: meter
    terrain_range: 7.5   # Unit: meter
    local_planner_range: 2.5   # Unit: meter
    visualize_ratio: 0.4
    is_viewpoint_extend: True
    is_multi_layer: False
    is_opencv_visual: False # Obstacle Image Display
    is_static_env: False
    is_pub_boundary: False
    is_debug_output: False
    is_attempt_autoswitch: True  # Auto switch to attemptable navigation
    world_frame: map

    # Graph Messager
    graph_msger/robot_id: 1  # graph from robot id `0` is extracted from files

    # Map Handler Params
    map_handler/floor_height: 1.5    # Unit: meter
    map_handler/cell_length: 1.5    # Unit: meter
    map_handler/map_grid_max_length: 300.0  # Unit: meter
    map_handler/map_grad_max_height: 15.0   # Unit: meter

    # Dynamic Planner Utility Params
    util/angle_noise: 15.0  # Unit: degree
    util/accept_max_align_angle: 4.0   # Unit: degree
    util/obs_inflate_size: 1
    util/new_intensity_thred: 2.0
    util/terrain_free_Z: 0.15
    util/dyosb_update_thred: 4
    util/new_point_counter: 5
    util/dynamic_obs_dacay_time: 2.0  # Unit: second
    util/new_points_decay_time: 1.0   # Unit: second

    # Dynamic Graph Params
    graph/connect_votes_size: 10
    graph/clear_dumper_thred: 4
    graph/node_finalize_thred: 6
    graph/filter_pool_size: 12

    # Corner Detector Params
    c_detector/resize_ratio: 3.0
    c_detector/filter_count_value: 6
    c_detector/is_save_img: False
    c_detector/img_folder_path: /path

    # Graph Planner Params
    g_planner/converge_distance: 0.4  # Unit: meter
    g_planner/goal_adjust_radius: 1.0  # Unit: meter
    g_planner/free_counter_thred: 7
    g_planner/reach_goal_vote_size: 3
    g_planner/path_momentum_thred: 3
