loam_interface:
  ros__parameters:
    use_sim_time: True
    loam_odometry_topic: pslam/imu_odom
    registered_scan_topic: pslam/aligned_scan_cloud
    map_cloud_topic: pslam/lio_map_cloud
    odom_frame: odom
    base_frame: base_footprint
    lidar_frame: mid360
    robot_base_frame: base_link

lio_3d_node:
  ros__parameters:
    use_sim_time: True
    lidar_type: livox
    # The `use_as_localizer` and `map_cloud_dir` does not need to be specified
    # since it going to be set by defaults in launch.
    # use_as_localizer:
    # map_cloud_dir:
    param_files_dir: $(find-pkg-share scorpio_nav_bringup)/params/reality

    pointcloud_topic: livox/lidar
    imu_topic: livox/imu

    imu_pose_topic: pslam/imu_pose
    imu_odom_topic: pslam/imu_odom
    lio_map_cloud_topic: pslam/lio_map_cloud
    aligned_scan_cloud_topic: pslam/aligned_scan_cloud
    deskewed_scan_cloud_topic: pslam/deskewed_scan_cloud

    odom_frame: pslam/odom
    imu_frame: pslam/mid360_imu
    publish_tf: False  # Whether to publish TF transform from `odom_frame` to `imu_frame`

slam_3d_node:
  ros__parameters:
    use_sim_time: True
    map_cloud_dir: tmp/pslam_data/
    param_files_dir: $(find-pkg-share scorpio_nav_bringup)/params/reality

    imu_pose_topic: pslam/imu_pose
    deskewed_scan_cloud_topic: pslam/deskewed_scan_cloud
    filtered_map_cloud_topic: pslam/filtered_map_cloud
    graph_nodes_topic: pslam/pose_graph_nodes
    odom_edges_topic: pslam/pose_graph_odom_edges
    loop_edges_topic: pslam/pose_graph_loop_edges

    map_frame: pslam/map
    # odometry and imu frames are defined in lio_3d_config.yaml
    publish_tf: False  # Whether to publish TF transform from `map_frame` to `odom_frame`

terrain_analysis:
  ros__parameters:
    use_sim_time: True
    odom_frame: odom
    lidar_frame: mid360
    scan_voxel_size: 0.05
    decay_time: 2.0
    no_decay_dis: 4.0
    clearing_dis: 8.0
    use_sorting: True
    quantile_z: 0.25
    consider_drop: False
    limit_ground_lift: False
    max_ground_lift: 0.15
    clear_dy_obs: False
    min_dy_obs_dis: 0.3
    abs_dy_obs_rel_z_thre: 0.2
    min_dy_obs_vfov: -16.0
    max_dy_obs_vfov: 16.0
    min_dy_obs_point_num: 1
    min_out_of_fov_point_num: 2
    obstacle_height_thre: 0.2
    no_data_obstacle: False
    no_data_block_skip_num: 0
    min_block_point_num: 10
    vehicle_height: 1.5
    min_rel_z: -1.5
    max_rel_z: 0.2
    dis_ratio_z: 0.2
    voxel_point_update_thre: 100
    voxel_time_update_thre: 2.0

terrain_analysis_ext:
  ros__parameters:
    use_sim_time: True
    odom_frame: odom
    lidar_frame: mid360
    terrain_voxel_size: 2.0
    terrain_voxel_width: 41
    planar_voxel_size: 0.4
    planar_voxel_width: 101
    voxel_point_count_thre: 100
    ground_elevation_thre: 0.5
    use_terrain_dyn_thre: 1.5
    check_terrain_conn: True
    terrain_under_vehicle: -0.75
    ceiling_filtering_thre: 2.0
    local_terrain_map_radius: 4.0
    downsize_filter_corner: 0.2
    downsize_filter_surface: 0.1
    point_decay_period: 10
    point_decay_ratio: 0.5
    vertical_angle_thre: 0.0
    max_terrain_angle: 30.0
    ground_z_thre: 0.1

far_planner:
  ros__parameters:
    use_sim_time: True
    # Dynamic Planner Default Params
    main_run_freq: 5.0
    voxel_dim: 0.1  # Unit: meter
    robot_dim: 0.5   # Unit: meter
    vehicle_height: 0.6  # Unit: meter
    sensor_range: 15.0  # Unit: meter
    terrain_range: 7.5   # Unit: meter
    local_planner_range: 2.5   # Unit: meter
    visualize_ratio: 0.4
    is_viewpoint_extend: True
    is_multi_layer: False
    is_opencv_visual: False # Obstacle Image Display
    is_static_env: False
    is_pub_boundary: False
    is_debug_output: False
    is_attempt_autoswitch: True  # Auto switch to attemptable navigation
    world_frame: map

    # Graph Messager
    graph_msger/robot_id: 1  # graph from robot id `0` is extracted from files

    # Map Handler Params
    map_handler/floor_height: 1.5    # Unit: meter
    map_handler/cell_length: 1.5    # Unit: meter
    map_handler/map_grid_max_length: 300.0  # Unit: meter
    map_handler/map_grad_max_height: 15.0   # Unit: meter

    # Dynamic Planner Utility Params
    util/angle_noise: 15.0  # Unit: degree
    util/accept_max_align_angle: 4.0   # Unit: degree
    util/obs_inflate_size: 1
    util/new_intensity_thred: 2.0
    util/terrain_free_Z: 0.15
    util/dyosb_update_thred: 4
    util/new_point_counter: 5
    util/dynamic_obs_dacay_time: 2.0  # Unit: second
    util/new_points_decay_time: 1.0   # Unit: second

    # Dynamic Graph Params
    graph/connect_votes_size: 10
    graph/clear_dumper_thred: 4
    graph/node_finalize_thred: 6
    graph/filter_pool_size: 12

    # Corner Detector Params
    c_detector/resize_ratio: 3.0
    c_detector/filter_count_value: 6
    c_detector/is_save_img: False
    c_detector/img_folder_path: /path

    # Graph Planner Params
    g_planner/converge_distance: 0.4  # Unit: meter
    g_planner/goal_adjust_radius: 1.0  # Unit: meter
    g_planner/free_counter_thred: 7
    g_planner/reach_goal_vote_size: 3
    g_planner/path_momentum_thred: 3
